### Test1 Api

GET http://localhost:1919/api

### Post Function

POST  http://localhost:1919/api
Content-Type: application/json

{
    "name" :"Arjun"
}

### Delete Function

DELETE  http://localhost:1919/api


